# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170701_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usertype',
            field=models.BooleanField(default=False),
        ),
    ]
