# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 03:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_auto_20170707_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='user_visit',
            field=models.ManyToManyField(related_name='product_visit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='category_show',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='order_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='order_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='order_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='order_volume',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='sort_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='sort_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='sort_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='sort_volume',
            field=models.BooleanField(default=False),
        ),
    ]
