from django.conf.urls import url, include
from . import store_views, product_views
urlpatterns = [
    url(r'^login_store/$',store_views.login_store, name = 'login_store'),
    url(r'^register_store/$',store_views.register_store, name = 'register_store'),
    url(r'^edit_store/$',store_views.edit_store, name = 'edit_store'),
    url(r'^logout_store/$', store_views.logout_store, name='logout_store'),
    url(r'^list_store/$', store_views.list_store, name='list_store'),
    url(r'^change_store_password/$', store_views.change_store_password, name='change_store_password'),
    url(r'^index_store/(?P<store_slug>[-\w]+)/$', store_views.index_store, name='index_store'),
    url(r'^add_product/(?P<store_slug>[-\w]+)/$', product_views.add_product, name='add_product'),
    url(r'^delete_product/(?P<store_slug>[-\w]+)/(?P<product_id>\d+)/$', product_views.delete_product, name='delete_product'),
    url(r'^edit_product/(?P<store_slug>[-\w]+)/(?P<product_id>\d+)/$', product_views.edit_product, name='edit_product'),
    url(r'^list_product/(?P<store_slug>[-\w]+)/$',product_views.list_product, name='list_product'),
    url(r'^detail_product/(?P<store_slug>[-\w]+)/(?P<product_id>\d+)/$', product_views.detail_product, name='detail_product'),
    url(r'^search_index/$', product_views.search_index, name='search_index'),
    url(r'^add_user_want/(?P<store_slug>[-\w]+)/(?P<product_id>\d+)/$', product_views.add_user_want, name='add_user_want'),
    url(r'^delete_user_want/(?P<store_slug>[-\w]+)/(?P<product_id>\d+)/$', product_views.delete_user_want, name='delete_user_want'),
    url(r'^index_product_want/$', product_views.index_product_want, name='index_product_want'),
    url(r'^index_product_visit/$', product_views.index_product_visit, name='index_product_visit'),
    url(r'^list_product_filter/(?P<store_slug>[-\w]+)/(?P<filter_type>\d+)/$', product_views.list_product_filter, name='list_product_filter'),
    url(r'^order_product_created/(?P<store_slug>[-\w]+)/$', product_views.order_product_created, name='order_product_created'),
    url(r'^order_product_price/(?P<store_slug>[-\w]+)/$', product_views.order_product_price, name='order_product_price'),
    url(r'^order_product_name/(?P<store_slug>[-\w]+)/$', product_views.order_product_name, name='order_product_name'),
    url(r'^order_product_volume/(?P<store_slug>[-\w]+)/$', product_views.order_product_volume, name='order_product_volume'),
    url(r'^sort_product_created/(?P<store_slug>[-\w]+)/$', product_views.sort_product_created, name='sort_product_created'),
    url(r'^sort_product_price/(?P<store_slug>[-\w]+)/$', product_views.sort_product_price, name='sort_product_price'),
    url(r'^sort_product_name/(?P<store_slug>[-\w]+)/$', product_views.sort_product_name, name='sort_product_name'),
    url(r'^sort_product_volume/(?P<store_slug>[-\w]+)/$', product_views.sort_product_volume, name='sort_product_volume'),
]
