# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='orderitem',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.OrderItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
