# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wait_recieved',
            field=models.BooleanField(default=False),
        ),
    ]
